script: echo hooray
notifications:
  webhooks:
    urls:
    - 'https://webhook-staging.atomist.services/atomist/travis/teams/T6PN80EKD'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
